// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEWjjsvwKQQumbrnSG4gTef9gHuPSJdug',
    appId: '1:733890391738:web:0a3fcba3722bb7e0eb1c83',
    messagingSenderId: '733890391738',
    projectId: 'e-commerc-c073f',
    authDomain: 'e-commerc-c073f.firebaseapp.com',
    storageBucket: 'e-commerc-c073f.appspot.com',
    measurementId: 'G-290PXFBGJC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQUOceOeBYUZUPxd1SrrZBYG7ybXfMizQ',
    appId: '1:733890391738:android:eb1fa9f30f0f10e1eb1c83',
    messagingSenderId: '733890391738',
    projectId: 'e-commerc-c073f',
    storageBucket: 'e-commerc-c073f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoZ1WOHzAcVXeOEsT7aCPtxD74QEw5fXM',
    appId: '1:733890391738:ios:00c201386736b248eb1c83',
    messagingSenderId: '733890391738',
    projectId: 'e-commerc-c073f',
    storageBucket: 'e-commerc-c073f.appspot.com',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAoZ1WOHzAcVXeOEsT7aCPtxD74QEw5fXM',
    appId: '1:733890391738:ios:00c201386736b248eb1c83',
    messagingSenderId: '733890391738',
    projectId: 'e-commerc-c073f',
    storageBucket: 'e-commerc-c073f.appspot.com',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBEWjjsvwKQQumbrnSG4gTef9gHuPSJdug',
    appId: '1:733890391738:web:caa37028dbba6150eb1c83',
    messagingSenderId: '733890391738',
    projectId: 'e-commerc-c073f',
    authDomain: 'e-commerc-c073f.firebaseapp.com',
    storageBucket: 'e-commerc-c073f.appspot.com',
    measurementId: 'G-2HHEVHFJDS',
  );
}
